<?xml version="1.0"?>
<robot name="object_1"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="object_1_z" value="0.0" />

  <property name="object_1_x" value="0.0" />
  <property name="object_1_y" value="0.0" />

  <property name="object_1_height"      value="0.12" />
  <property name="object_1_radius"      value="0.02" />
  <property name="object_1_base_height" value="0.02" />
  <property name="object_1_base_width"  value="0.15" />
  <property name="object_1_mass"        value="0.2" /> 
  <property name="object_1_mu"          value="500.0" /> 
  <joint name="object_1_joint" type="fixed" >
    <parent link="object_1_base_link" />
    <origin xyz="0 0 ${object_1_base_height}" rpy="0 0 0" />
    <child link="object_1_link" />
  </joint> 
  <link name="object_1_link">
    <inertial>
      <mass value="${object_1_mass/2.0}" />
      <origin xyz="0 0 ${object_1_height/2}" />
      <inertia ixx="${object_1_mass/20.0}" ixy="0"  ixz="0"
               iyy="${object_1_mass/20.0}" iyz="0"
               izz="${object_1_mass/200.}" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${object_1_height/2}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${object_1_radius}" length="${object_1_height}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${object_1_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${object_1_radius}" length="${object_1_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="object_1_link">
    <material>Gazebo/BumpyMetal</material>
    <mu1>${object_1_mu}</mu1>
    <mu2>${object_1_mu}</mu2>
    <kp>100000000.0</kp>
    <kd>10000000.0</kd>
    <maxVel>1.0</maxVel>
    <turnGravityOff>true</turnGravityOff>
    <dampingFactor>0.001</dampingFactor>
  </gazebo>

  <link name="world" />
  <joint name="object_1_base_joint" type="planar" >
    <parent link="world" />
    <origin xyz="${object_1_x} ${object_1_y} ${object_1_z}" rpy="0 0 0" />
    <child link="object_1_base_link" />
  </joint> 
  <link name="object_1_base_link">
    <inertial>
      <mass value="${object_1_mass/2.0}" />
      <origin xyz="0 0 ${object_1_base_height/2}" />
      <inertia ixx="${object_1_mass/20.0}" ixy="0"  ixz="0"
               iyy="${object_1_mass/20.0}" iyz="0"
               izz="${object_1_mass/200.}" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${object_1_base_height/2}" rpy="0 0 0" />
      <geometry>
        <box size="${object_1_base_width} ${object_1_base_width} ${object_1_base_height}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${object_1_base_height/2}" rpy="0.0 0.0 0.0" />
      <geometry>
        <box size="${object_1_base_width} ${object_1_base_width} ${object_1_base_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="object_1_base_link">
    <material>Gazebo/RustyBarrel</material>
    <mu1>500.0</mu1>
    <mu2>500.0</mu2>
    <kp>100000000.0</kp>
    <kd>10000000.0</kd>
    <maxVel>1.0</maxVel>
    <turnGravityOff>true</turnGravityOff>
    <dampingFactor>0.001</dampingFactor>
  </gazebo>

</robot>
